import type { QuizSet } from "../../types/quiz";

export const sampleQuizSet: QuizSet = {
  id: "grade6-class1-april-social-golden-bell",
  subject: "사회",
  setName: "4월 사회",
  title: "6학년 1반 4월 도전 골든벨 (사회)",
  subtitle: "사이버틱 에디션 | 1단원 평화 통일을 위한 노력, 민주화와 산업화",
  themeColor: "#00D7FF",
  rules: [
    "문제를 확인한 뒤 손들고 말하기",
    "O/X 퀴즈에서 손을 어중간하게 들면 탈락",
    "별 점수와 난이도는 * = 1, ** = 2, *** = 3",
    "DOUBLE 표시가 있는 문제는 점수가 2배",
    "정답 힌트 주지 않기, 잡담 금지, 남피!!",
    "틀려도 괜찮아요. 친구를 응원하기",
  ],
  questions: [
    {
      id: "q-01",
      order: 1,
      type: "short_text",
      prompt: "단원 제목: 〈 _ _  _ _ 을 위한 노력, _ _ _ 와 _ _ _ 〉",
      answerText: "평화 통일, 민주화, 산업화",
      points: 2,
      difficulty: 2,
      timerSeconds: 20,
      explanation: "단원 제목의 핵심 낱말 3개를 모두 말하면 정답입니다.",
    },
    {
      id: "q-02",
      order: 2,
      type: "short_text",
      prompt: "‘분단으로 고향을 잃은 _ _ _ 과 가족을 잃은 _ _  _ _ 은 여전히 분단의 아픔을 가지고 살고 있습니다.’",
      answerText: "실향민, 이산 가족",
      points: 1,
      difficulty: 1,
      timerSeconds: 15,
    },
    {
      id: "q-03",
      order: 3,
      type: "ox",
      prompt: "분단 비용이란 우리나라가 분단되어 있어 발생하는 비용이다.",
      correctChoice: "O",
      points: 1,
      difficulty: 1,
      timerSeconds: 12,
    },
    {
      id: "q-04",
      order: 4,
      type: "ox",
      prompt: "DMZ 평화의 길은 비무장 지대 전체를 남과 북의 합의를 통해 개방하여 사람들이 관람할 수 있도록 만들었습니다.",
      correctChoice: "X",
      points: 1,
      difficulty: 1,
      timerSeconds: 12,
      explanation: "일부 구간만 개방해 운영하고 있습니다.",
    },
    {
      id: "q-05",
      order: 5,
      type: "short_text",
      prompt: "비무장지대는 군사 분계선을 기준으로 남과 북 각각 몇 km 범위에 설정했나요?",
      answerText: "2",
      points: 2,
      difficulty: 2,
      timerSeconds: 18,
    },
    {
      id: "q-06",
      order: 6,
      type: "short_text",
      prompt: "‘평화 통일을 위한 노력에는 _ _ _ 노력, _ _ _ 노력, _ _  _ _ _ 노력이 있다.’",
      answerText: "정치적, 경제적, 사회 문화적",
      points: 1,
      difficulty: 1,
      timerSeconds: 18,
    },
    {
      id: "q-07",
      order: 7,
      type: "short_text",
      prompt: "남북정상회담을 진행한 대통령은 누구일까요? (순서대로)",
      answerText: "김대중, 노무현, 문재인",
      points: 2,
      difficulty: 2,
      timerSeconds: 22,
    },
    {
      id: "q-08",
      order: 8,
      type: "multiple_choice",
      prompt: "(더블 포인트) 『_ _ _  _ _ _』은 남북 공동 편찬 사업을 진행한 통일 국어사전입니다. 이 사전의 이름은?",
      choices: ["한나라큰사전", "새누리큰사전", "겨레말큰사전", "우리말큰사전"],
      correctChoiceIndex: 2,
      points: 4,
      difficulty: 2,
      timerSeconds: 20,
      bonusLabel: "DOUBLE",
      explanation: "기본 난이도는 ★★, DOUBLE이라 점수는 ★★★★입니다.",
    },
    {
      id: "q-09",
      order: 9,
      type: "short_text",
      prompt: "‘1998년에 시작된 _ _ _ 관광 사업은 민간 차원의 남북 교류를 넓히는 데 많은 도움이 되었다.’",
      answerText: "금강산",
      points: 1,
      difficulty: 1,
      timerSeconds: 15,
    },
    {
      id: "q-10",
      order: 10,
      type: "short_text",
      prompt: "우리나라와 북한이 분단 이후 최초로 단일팀으로 출전한 대회의 이름은? (책 OK)",
      answerText: "제41회 세계 탁구 선수권 대회",
      points: 3,
      difficulty: 3,
      timerSeconds: 30,
      explanation: "책을 봐도 되는 긴 정답 문항입니다.",
    },
    {
      id: "q-11",
      order: 11,
      type: "ox",
      prompt: "북한 연구자는 북한 사회에 관한 이해를 바탕으로 분단된 나라를 통일하고 남북이 하나가 될 수 있는 방법을 연구합니다.",
      correctChoice: "O",
      points: 2,
      difficulty: 2,
      timerSeconds: 12,
    },
    {
      id: "q-12",
      order: 12,
      type: "short_text",
      prompt: "대한민국의 초대 대통령인 이승만은 헌법을 바꿔 가며 몇 차례 대통령이 되었을까요?",
      answerText: "3차례",
      points: 1,
      difficulty: 1,
      timerSeconds: 15,
    },
    {
      id: "q-13",
      order: 13,
      type: "short_text",
      prompt: "‘마산 시위에 참여했던 고등학생 _ _ _ 의 시신이 발견되면서 시위는 전국적으로 퍼졌다.’",
      answerText: "김주열",
      points: 1,
      difficulty: 1,
      timerSeconds: 15,
    },
    {
      id: "q-14",
      order: 14,
      type: "ox",
      prompt: "4·19 혁명으로 이승만은 대통령 자리에서 물러났고, 3·15 부정 선거는 무효가 되었다.",
      correctChoice: "O",
      points: 1,
      difficulty: 1,
      timerSeconds: 12,
    },
    {
      id: "q-15",
      order: 15,
      type: "short_text",
      prompt: "(깜짝 문제) 문화어 ‘사탕가루’는 한국어로 무엇일까요?",
      answerText: "설탕",
      points: 2,
      difficulty: 2,
      timerSeconds: 15,
      bonusLabel: "SURPRISE",
    },
    {
      id: "q-16",
      order: 16,
      type: "ox",
      prompt: "박정희의 장기 집권은 부하의 암살로 막을 내렸다.",
      correctChoice: "O",
      points: 1,
      difficulty: 1,
      timerSeconds: 12,
    },
    {
      id: "q-17",
      order: 17,
      type: "ox",
      prompt: "폭력에 분노한 광주 시민은 계엄군을 만들어 대항했다.",
      correctChoice: "X",
      points: 1,
      difficulty: 1,
      timerSeconds: 12,
      explanation: "광주 시민군을 만들어 맞섰습니다.",
    },
    {
      id: "q-18",
      order: 18,
      type: "short_text",
      prompt: "(더블 포인트) 5·18 민주화 운동을 세상에 알린 외국인 기자의 이름은? (NO 책)",
      answerText: "위르겐 힌츠페터",
      points: 6,
      difficulty: 3,
      timerSeconds: 25,
      bonusLabel: "DOUBLE",
      explanation: "기본 난이도는 ★★★, DOUBLE이라 점수는 ★★★★★★입니다.",
    },
    {
      id: "q-19",
      order: 19,
      type: "manual",
      prompt: "순서를 맞추시오: 1. 12·12 군사정변 2. 5·16 군사정변 3. 3·15 부정선거 4. 4·19 혁명 5. 5·18 민주화 운동 6. 6·29 민주화 선언",
      answerText: "3 → 4 → 2 → 1 → 5 → 6",
      points: 2,
      difficulty: 2,
      timerSeconds: 25,
      explanation: "손들고 순서를 끝까지 말하면 됩니다.",
    },
    {
      id: "q-20",
      order: 20,
      type: "ox",
      prompt: "대학생 이한열의 고문치사사건으로 일어난 6월 민주 항쟁에서 대학생 박종철이 머리에 최루탄을 맞았다.",
      correctChoice: "X",
      points: 2,
      difficulty: 2,
      timerSeconds: 12,
      explanation: "박종철은 고문 끝에 숨졌고, 이한열이 최루탄에 맞았습니다.",
    },
    {
      id: "q-21",
      order: 21,
      type: "short_text",
      prompt: "6·29 민주화 선언을 발표한 사람의 이름은?",
      answerText: "노태우",
      points: 1,
      difficulty: 1,
      timerSeconds: 15,
    },
    {
      id: "q-22",
      order: 22,
      type: "ox",
      prompt: "지방 자치 제도는 ‘풀뿌리 민주주의’라는 별명이 있다.",
      correctChoice: "O",
      points: 2,
      difficulty: 2,
      timerSeconds: 12,
      explanation: "‘꽃부리’가 아니라 ‘풀뿌리 민주주의’입니다.",
    },
    {
      id: "q-23",
      order: 23,
      type: "short_text",
      prompt: "‘밀가루, 설탕, 면직물을 만드는 산업은 _ _ 산업이다.’",
      answerText: "삼백",
      points: 1,
      difficulty: 1,
      timerSeconds: 15,
    },
    {
      id: "q-24",
      order: 24,
      type: "ox",
      prompt: "1960년대에 정부는 중화학 공업을 발전시켰다.",
      correctChoice: "X",
      points: 2,
      difficulty: 2,
      timerSeconds: 12,
      explanation: "중화학 공업 육성은 1970년대에 본격화되었습니다.",
    },
    {
      id: "q-25",
      order: 25,
      type: "ox",
      prompt: "1980년대에 중화학 공업이 더욱 발달하여 국민 소득이 완만히 늘어났다.",
      correctChoice: "X",
      points: 2,
      difficulty: 2,
      timerSeconds: 12,
      explanation: "국민 소득은 빠르게 증가했습니다.",
    },
    {
      id: "q-26",
      order: 26,
      type: "short_text",
      prompt: "‘정부는 도시에 지하철을 개통하고, 고속 국도를 확대하여 전국을 _ _ _ _ _ 으로 만들었다.’",
      answerText: "일일생활권",
      points: 2,
      difficulty: 2,
      timerSeconds: 18,
    },
    {
      id: "q-27",
      order: 27,
      type: "short_text",
      prompt: "‘소득 수준이 높아지며 라디오, 텔레비전과 같은 대중문화가 보급되고, 가요, 드라마, 스포츠 등 _ _ _ _ 가 성장했다.’",
      answerText: "대중 문화",
      points: 1,
      difficulty: 1,
      timerSeconds: 15,
    },
    {
      id: "q-28",
      order: 28,
      type: "short_text",
      prompt: "안정된 일자리를 찾지 못한 사람은 도시의 변두리나 ‘이곳’에 자리 잡았다. 이곳은 어디인가? (NO 책)",
      answerText: "달동네",
      points: 3,
      difficulty: 3,
      timerSeconds: 20,
    },
    {
      id: "q-29",
      order: 29,
      type: "ox",
      prompt: "1960~70년대 수입 중심의 정책을 추진한 정부는 수입품의 가격을 낮춰 경쟁력을 유지했다.",
      correctChoice: "X",
      points: 2,
      difficulty: 2,
      timerSeconds: 12,
      explanation: "수출 중심 정책으로 경쟁력을 키웠습니다.",
    },
    {
      id: "q-30",
      order: 30,
      type: "ox",
      prompt: "도시 재생 전문가는 쇠퇴하거나 오래된 도시를 되살릴 수 있도록 도시 재생 계획을 세우는 일을 합니다.",
      correctChoice: "O",
      points: 1,
      difficulty: 1,
      timerSeconds: 12,
    },
  ],
};
