import type { QuizSet } from "../../types/quiz";

export const sampleQuizSet: QuizSet = {
  id: "sample-korean-grade6-march",
  subject: "국어",
  setName: "3월 국어 골든벨",
  title: "6학년 1반 3월 국어 골든벨",
  subtitle: "PPT 분위기와 템포를 반영한 데모 세트",
  themeColor: "#4472C4",
  rules: [
    "문제를 읽고 진행자의 신호에 맞춰 정답을 공개해요.",
    "정답 여부는 교사가 확인하고 점수를 반영해요.",
    "보너스 문항은 제시된 점수만큼 추가 점수를 받아요.",
    "끝까지 집중해서 높은 점수를 노려 보세요.",
  ],
  questions: [
    {
      id: "q-01",
      order: 1,
      type: "short_text",
      prompt: "(인물의 마음) ___ 와 관련된 낱말을 써요.",
      answerText: "자신의 삶",
      points: 1,
      timerSeconds: 20,
      explanation: "1단원 핵심 표현을 떠올리면 쉬워요.",
    },
    {
      id: "q-02",
      order: 2,
      type: "short_text",
      prompt: "사람들이 자신의 삶에 대해 중요하게 여기는 것을 __ 라고 해요.",
      answerText: "가치",
      points: 1,
      timerSeconds: 20,
    },
    {
      id: "q-03",
      order: 3,
      type: "ox",
      prompt: "시의 한 갈래인 동시는 글쓴이의 실제 경험에서만 만들어진다.",
      correctChoice: "X",
      points: 2,
      timerSeconds: 15,
    },
    {
      id: "q-04",
      order: 4,
      type: "manual",
      prompt: "2단원의 이름은 무엇일까요? 가장 먼저 손든 친구에게 기회를 주세요.",
      answerText: "바르게 고쳐 써요",
      points: 2,
      bonusLabel: "SURPRISE",
      explanation: "손들기 문항은 학생 전체 자동 채점 대신 선택 학생에게 점수를 줄 수 있어요.",
    },
    {
      id: "q-05",
      order: 5,
      type: "multiple_choice",
      prompt: "설명하는 글에서 어떤 대상을 다른 것에 빗대어 말하는 방법은 무엇일까요?",
      choices: ["비유", "원인", "비교", "예측"],
      correctChoiceIndex: 0,
      points: 3,
      timerSeconds: 25,
      explanation: "배포판에서도 객관식 문항 흐름을 바로 확인할 수 있도록 넣어둔 예시예요.",
    },
    {
      id: "q-06",
      order: 6,
      type: "ox",
      prompt: "하루의 일기를 쓰게 되면 자신의 생활을 중요하게 생각하게 된다.",
      correctChoice: "O",
      points: 3,
      timerSeconds: 15,
      bonusLabel: "마지막 문제",
    },
  ],
};
