import type { QuizSet } from "../../types/quiz";

export const sampleQuizSet: QuizSet = {
  id: "sample-korean-grade6-march",
  subject: "국어",
  setName: "3월 국어 골든벨",
  title: "6학년 1반 3월 국어 골든벨",
  subtitle: "PPT 흐름을 웹앱 운영용으로 옮긴 데모 세트",
  themeColor: "#4472C4",
  rules: [
    "문제를 읽은 뒤 진행자의 신호에 맞춰 정답을 공개해요.",
    "정답 여부는 교사가 확인하고 점수를 반영해요.",
    "보너스 문항은 표시된 점수만큼 추가 점수를 받아요.",
    "끝까지 집중해서 높은 점수를 노려봐요.",
  ],
  questions: [
    {
      id: "q-01",
      order: 1,
      type: "short_text",
      prompt: "(단원 제목) ___ 과 관련지어 읽어요.",
      answerText: "자신의 삶",
      points: 1,
      timerSeconds: 20,
      explanation: "1단원 핵심 표현을 떠올리면 쉬워요.",
    },
    {
      id: "q-02",
      order: 2,
      type: "short_text",
      prompt: "사람들이 자신의 삶에서 중요하게 여기는 것을 __ 라고 해요.",
      answerText: "가치",
      points: 1,
      timerSeconds: 20,
    },
    {
      id: "q-03",
      order: 3,
      type: "ox",
      prompt: "윤희순은 나라의 주권이 빼앗기자 한국에서 독립운동을 주도했다.",
      correctChoice: "X",
      points: 2,
      timerSeconds: 15,
    },
    {
      id: "q-04",
      order: 4,
      type: "manual",
      prompt: "2단원의 이름은 무엇인가요? 가장 먼저 손든 친구에게 기회를 주세요.",
      answerText: "바르게 고쳐 써요",
      points: 2,
      bonusLabel: "SURPRISE",
      explanation: "손들기 문항은 학생 전체 자동 채점 대신 선택 학생에게 점수를 줄 수 있어요.",
    },
    {
      id: "q-05",
      order: 5,
      type: "short_text",
      prompt: "'뛰면서 계속 생각해. 최고로 아름다운 __ 을 해야지.' 빈칸을 채워 보세요.",
      answerText: "비행",
      points: 3,
      timerSeconds: 25,
    },
    {
      id: "q-06",
      order: 6,
      type: "ox",
      prompt: "나루는 끈기 있게 도전하는 것을 중요하게 생각한다.",
      correctChoice: "O",
      points: 3,
      timerSeconds: 15,
      bonusLabel: "마지막 문제",
    },
  ],
};
